services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
  back-end:
    image: "routes:0.0.1"
    container_name: routes
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  front-end:
    image: "frontend:0.0.1"
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - back-end
