services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5433:5433'
    network_mode: "host"
  backend:
    image: "routes:0.0.1"
    container_name: routes
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  frontend:
    image: "frontend:0.0.1"
    container_name: frontend
    ports:
      - "3000:3000"
    links:
      - backend
