services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  back-end:
    image: "routes:0.0.1"
    container_name: routes
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  frontend:
    build: .
    command: npm start
    x-develop:
      watch:
        - action: sync
          path: ./frontend
          target: /src/frontend
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend/package.json
